feat: Add MultipleClassification and clustering web service
cohostai/internship pull request #2
Opened 2022-03-10 04:48 UTC by cuong3004

2022-03-10 07:43 UTC, dungdl commented on CategoryWebService/cluster_service.py
> +df = pd.read_csv("data.csv")
không commit file data lên repo Github nhé em. cần đưa các file .csv vào file .gitignore

2022-03-10 07:43 UTC, dungdl commented on CategoryWebService/cluster_service.py
> +# tiền sử lý text, tạo thành các đầu vào phù hợp cho model
xử lý

2022-03-10 07:46 UTC, dungdl commented on CategoryWebService/main.py
> +with open('intents_list.pkl', 'rb') as f:
tạo 1 file constants.py -> tải tên file này từ biến môi trường.
VD: có 1 biến môi trường là $INTENT_FILE = './source/intents_list.pkl'
Nhiệm vụ của file constantas.py: đọc biến $INTENT_FILE từ biến môi trường và lưu ra 1 biến trong Python là INTENT_FILE.
Trong file main.py gọi lại biến INTENT_FILE ở câu lệnh mở file (with open())

2022-03-10 07:48 UTC, dungdl commented on CategoryWebService/main.py
> +label1_dir = {k:v for v, k in enumerate(label1_list)}
label1 là gì? label2 là gì?

2022-03-10 07:49 UTC, dungdl commented on CategoryWebService/main.py
> +    return {
refactor lại thành 1 Class

2022-03-10 07:50 UTC, dungdl commented on CategoryWebService/main.py
> +class HelloWorld(Resource):
sửa tên Class

2022-03-10 07:51 UTC, dungdl commented on CategoryWebService/templates/clustering.html
> +  <h1>Hello Plotly (but not Dash)</h1>
Custom lại theo ý em

2022-03-10 07:51 UTC, dungdl commented on CategoryWebService/test.py
> +# params = {'q': 'Xin Chào'}
viết mô tả cho file này

2022-03-10 07:52 UTC, dungdl requested changes
Sửa lại theo các comment của từng file

2022-03-12 03:18 UTC, cuong3004 commented on CategoryWebService/cluster_service.py
> +df = pd.read_csv("data.csv")
em đã sửa rùi

2022-03-16 08:05 UTC, dungdl commented
@cuong3004 em xử lý các comment và đóng lại nhé, ưu tiên task này trước nhé

2022-03-16 09:09 UTC, cuong3004 commented on CategoryWebService/cluster_service.py
> +# tiền sử lý text, tạo thành các đầu vào phù hợp cho model
Em sửa lại rùi

2022-03-16 09:10 UTC, cuong3004 commented on CategoryWebService/main.py
> +with open('intents_list.pkl', 'rb') as f:
Vì môi trưng Win làm việc hơi khó, nên em chỉ đành lưu các biến này ra một file config

2022-03-16 09:11 UTC, cuong3004 commented on CategoryWebService/main.py
> +label1_dir = {k:v for v, k in enumerate(label1_list)}
Em có ghi chú thích lại rùi

2022-03-16 09:11 UTC, cuong3004 commented on CategoryWebService/main.py
> +    return {
Em chuyển lại thành một class riêng

2022-03-16 09:13 UTC, cuong3004 commented on CategoryWebService/templates/clustering.html
> +  <h1>Hello Plotly (but not Dash)</h1>
Cái phần cluster service em sẽ commit sau

2022-03-16 09:13 UTC, cuong3004 commented on CategoryWebService/test.py
> +# params = {'q': 'Xin Chào'}
Em viết mô tả trong readme rùi

2022-03-16 09:13 UTC, cuong3004 commented
Đã trả lời hết các commend

2022-03-17 10:56 UTC, dungdl commented on CategoryWebService/config.py
> +DATA_FILE = "file_store/data.csv"
@cuong3004 phần này trước anh nói là em đọc từ biến môi trường mà. ví dụ:
DATA_FILE = os.getenv('DATA_FILE', 'file_store/data.csv')

2022-03-17 10:56 UTC, dungdl commented on CategoryWebService/config.py
> +DATA_FILE = "file_store/data.csv"
sửa lại file này nhé

2022-03-17 10:57 UTC, dungdl commented on CategoryWebService/none.py
> +import pickle
file này để làm gì nhỉ?

2022-03-17 10:58 UTC, dungdl commented on CategoryWebService/requirements.txt
> +aniso8601==9.0.1
em không dùng pipenv à @cuong3004

2022-03-17 10:58 UTC, dungdl commented on CategoryWebService/train.py
> +class CusttomData(Dataset):
CustomData nhé, sửa chính tả này @cuong3004

2022-03-17 10:59 UTC, dungdl commented on CategoryWebService/train.py
> +        loss = 0.7 * loss1 + 0.3 * loss2
hệ số 0.7 và 0.3 sao cần fix cứng như này nhỉ? @cuong3004

2022-03-17 10:59 UTC, dungdl requested changes
Một số chỗ cần sửa và làm rõ

2022-03-18 08:22 UTC, cuong3004 commented on CategoryWebService/config.py
> +DATA_FILE = "file_store/data.csv"
Em đã sửa lại

2022-03-18 08:22 UTC, cuong3004 commented on CategoryWebService/none.py
> +import pickle
File em quên xóa  :))

2022-03-18 08:23 UTC, cuong3004 commented on CategoryWebService/requirements.txt
> +aniso8601==9.0.1
Bây giờ thì em dùng :))

2022-03-18 08:33 UTC, cuong3004 commented on CategoryWebService/train.py
> +class CusttomData(Dataset):
Em sửa lại rùi

2022-03-18 08:34 UTC, cuong3004 commented on CategoryWebService/train.py
> +        loss = 0.7 * loss1 + 0.3 * loss2
Là một cách để tối ưu hóa, đẻ model ưu tiên train nhận diện intent hơn category

2022-03-18 08:39 UTC, cuong3004 commented
Em sửa lại rùi

2022-03-21 09:39 UTC, dungdl commented on CategoryWebService/requirements.txt
> +aniso8601==9.0.1
em vẫn đang dùng requirements.txt mà

2022-03-21 09:41 UTC, dungdl commented on CategoryWebService/train.py
> +        loss = 0.7 * loss1 + 0.3 * loss2
cái này mình có thay đổi nhiều không em? nếu thay đổi nhiều em đẩy ra biến môi trường nhé

2022-03-21 09:42 UTC, dungdl reviewed
@cuong3004 em trả lời các comment còn lại của anh nhé, còn lại ok rồi, nếu không cần thay đổi nữa thì request review của anh lần nữa nhé

2022-03-21 09:44 UTC, dungdl commented on CategoryWebService/train.py
> +class CusttomData(Dataset):
chưa thấy đẩy code sửa lên đây em? @cuong3004

2022-03-21 09:44 UTC, dungdl commented on CategoryWebService/train.py
> +data_train = CusttomData(df)
@cuong3004 đây nữa này em

2022-03-23 07:26 UTC, cuong3004 commented on CategoryWebService/requirements.txt
> +aniso8601==9.0.1
Để chỉnh sửa sau

2022-03-23 07:34 UTC, cuong3004 commented on CategoryWebService/train.py
> +        loss = 0.7 * loss1 + 0.3 * loss2
Sửa lại sau

2022-03-23 07:49 UTC, dungdl approved these changes

2022-03-23 07:49 UTC, merged