Cuongdc/category web service
cohostai/internship pull request #5
Opened 2022-03-24 03:53 UTC by cuong3004

2022-03-25 03:42 UTC, dungdl commented on CategoryWebService/Pipfile
> +[[source]]
![Screen Shot 2022-03-25 at 10 41 58](https://user-images.githubusercontent.com/33054551/160049972-14bcfca7-145f-4009-90d4-868a0e22ff67.png)
@cuong3004 pipenv chưa hoạt động em ơi, vẫn thiếu lib

2022-03-25 03:44 UTC, dungdl requested changes
em kiểm tra lại phần sử dụng pipenv nhé, vẫn đang thiếu lib nên chưa chạy được service @cuong3004

2022-03-26 05:01 UTC, cuong3004 commented on CategoryWebService/Pipfile
> +[[source]]
Em đã sử lại rùi ạ

2022-03-26 05:02 UTC, cuong3004 commented
Em đã sửa lại. anh thử lại nhé

2022-03-31 10:30 UTC, dungdl commented on CategoryWebService/model.py
> +    backbone = AutoModel.from_pretrained(
@cuong3004 mình cần đẩy các bộ hỗ trợ này ra biến môi trường, chỉ download 1 lần thôi. như thế này mỗi lần chạy mới lại download sẽ có nhiều rủi ro

2022-03-31 10:30 UTC, dungdl approved these changes

2022-03-31 10:31 UTC, merged